variable "business_unit" {
  type        = string
  description = "Business unit of the project, such as HR, IT, or Sales"
}

variable "stage" {
  type        = string
  description = <<-EOT
    Stage of the environment to be setup up.
    Possible values: `Dev`, `Test`, `Prod`, `Shared`.
  EOT

  validation {
    condition     = contains(["Dev", "Test", "Prod", "Shared"], var.stage)
    error_message = "Stage must be one of the following: `Dev`, `Test`, `Prod`, `Shared`."
  }
}

variable "company_name" {
  type        = string
  description = <<-EOT
    Company name to be used for subaccount subdomains. The parameter is optional
    Default value: `null`.
  EOT
  default     = null
}

variable "costcenter" {
  type        = string
  description = "Cost center to be used for subaccounts"
}

variable "subaccount_contacts" {
  type        = list(string)
  description = "Contact persons to be used for subaccounts, added as label"
}

variable "add_managed_by_label" {
  type        = bool
  description = <<-EOT
  Add label that the resource is managed by Terraform
  Default value: `true`
  EOT
  default     = true
}

variable "management_tool" {
  type        = string
  description = <<-EOT
    The tool that's used to manage the infrastructure.
    Possible values: `Terraform`, `OpenTofu`.
    Default value: `Terraform`.
  EOT

  validation {
    condition     = contains(["Terraform", "OpenTofu"], var.management_tool)
    error_message = "Allowed values are: `Terraform`, `OpenTofu`."
  }
  default = "Terraform"
}

variable "delimiter" {
  type        = string
  description = "Delimiter to be used for namings"
  default     = "-"
}

variable "label_name_case" {
  type        = string
  default     = "title"
  description = <<-EOT
    Controls the capitalization of the `label` names for labels generated by this module.
    Possible values: `lower`, `title`, `upper`.
    Default value: `title`.
  EOT

  validation {
    condition     = contains(["lower", "title", "upper"], var.label_name_case)
    error_message = "Allowed values are: `lower`, `title`, `upper`."
  }
}

variable "label_value_case" {
  type        = string
  default     = "lower"
  description = <<-EOT
    Controls the capitalization of the `label` values for labels generated by this module.
    Possible values: `lower`, `title`, `upper` and `none` (no transformation).
    Default value: `lower`.
  EOT

  validation {
    condition     = contains(["lower", "title", "upper", "none"], var.label_value_case)
    error_message = "Allowed values are: `lower`, `title`, `upper`, `none`."
  }
}
